### ISSUE TITLE
Error in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors") :    Rle of type 'list' is not supported

### ISSUE THREAD

**Issue by tida-one** [davidszkiba/snp2go#6]
Hello, 
I am trying to use SNP2GO with a gff3 annotation file. It starts reading the  file (Reading Pacla8A.gff3) and crashes with error: 

`Error in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors") : 
  Rle of type 'list' is not supported`

I tried to run the same command line with my SNP data but another "gff" and it works nicely. So the problem should come from the annotation file but I have no idea of where/what to look since everything looks fine (9 columns, "Ontology_term" etc). 

I am quite lost with this annotation since it was done in another lab and this is a bit far from my skills. Any input would be very welcome. 
Thank you

Here is the command line I use:
```
candidates <- read.delim("signif_snps.vcf",sep = " ", header=FALSE,comment.char="#")
candidates[,2] <- as.numeric(candidates[,2])

noncandidates <- read.delim("all_snps.vcf",sep = " ", header=FALSE,comment.char="#")
noncandidates[,2] <- as.numeric(noncandidates[,2])

snps_cand <- GRanges(seqnames=candidates[,1],ranges=IRanges(candidates[,2],candidates[,2]))
snps_non_cand <- GRanges(seqnames=noncandidates[,1],ranges=IRanges(noncandidates[,2],noncandidates[,2]))


x <- snp2go(gff="Pacla8A.gff3",
            candidateSNPs=snps_cand,
            noncandidateSNPs=snps_non_cand)
```
Here are the first lines of the gff3:

`pcla8_s000007   CNAG    gene    34      20855   .       +       .       ID=Pacla8A056872;gene_type=protein_coding
pcla8_s000007   CNAG    transcript      34      18362   .       +       .       ID=Pacla8A056872T1;Parent=Pacla8A056872;Name=Pacla8A056872T1;product=Pacla8A056872P1;gene_type=protein_coding;transcript_biotype=protein_coding;Description=ABC transporter G family member 21 , partial;Ontology_term=GO:0004871%2C GO:0005516%2C GO:0005524%2C GO:0005737%2C GO:0007165%2C GO:0016020%2C GO:0016887
pcla8_s000007   CNAG    exon    34      72      .       +       .       ID=Pacla8A056872T1.exon1;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    153     259     .       +       .       ID=Pacla8A056872T1.exon2;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    464     527     .       +       .       ID=Pacla8A056872T1.exon3;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    599     674     .       +       .       ID=Pacla8A056872T1.exon4;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    1050    1136    .       +       .       ID=Pacla8A056872T1.exon5;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    1261    1327    .       +       .       ID=Pacla8A056872T1.exon6;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    3057    3186    .       +       .       ID=Pacla8A056872T1.exon7;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    3260    3278    .       +       .       ID=Pacla8A056872T1.exon8;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    3330    3331    .       +       .       ID=Pacla8A056872T1.exon9;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    3438    3515    .       +       .       ID=Pacla8A056872T1.exon10;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    3779    3781    .       +       .       ID=Pacla8A056872T1.exon11;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    5357    5364    .       +       .       ID=Pacla8A056872T1.exon12;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    8738    8898    .       +       .       ID=Pacla8A056872T1.exon13;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    10123   10298   .       +       .       ID=Pacla8A056872T1.exon14;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    10658   10714   .       +       .       ID=Pacla8A056872T1.exon15;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    10819   10867   .       +       .       ID=Pacla8A056872T1.exon16;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    10992   11027   .       +       .       ID=Pacla8A056872T1.exon17;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    12131   12195   .       +       .       ID=Pacla8A056872T1.exon18;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    12813   12974   .       +       .       ID=Pacla8A056872T1.exon19;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    13191   13284   .       +       .       ID=Pacla8A056872T1.exon20;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    13444   13504   .       +       .       ID=Pacla8A056872T1.exon21;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    15295   15853   .       +       .       ID=Pacla8A056872T1.exon22;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    16087   16170   .       +       .       ID=Pacla8A056872T1.exon23;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    16476   16533   .       +       .       ID=Pacla8A056872T1.exon24;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    16839   17053   .       +       .       ID=Pacla8A056872T1.exon25;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    17585   17793   .       +       .       ID=Pacla8A056872T1.exon26;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    exon    18176   18362   .       +       .       ID=Pacla8A056872T1.exon27;Parent=Pacla8A056872T1;Name=Pacla8A056872T1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     34      72      .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     153     259     .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     464     527     .       +       1       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     599     674     .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     1050    1136    .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     1261    1327    .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     3057    3186    .       +       1       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     3260    3278    .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     3330    3331    .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     3438    3515    .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     3779    3781    .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     5357    5364    .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     8738    8898    .       +       1       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     10123   10298   .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     10658   10714   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     10819   10867   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     10992   11027   .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     12131   12195   .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     12813   12974   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     13191   13284   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     13444   13504   .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     15295   15853   .       +       1       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     16087   16170   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     16476   16533   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     16839   17053   .       +       2       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     17585   17793   .       +       0       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    CDS     18176   18362   .       +       1       ID=Pacla8A056872C1;Parent=Pacla8A056872T1;Name=Pacla8A056872C1;gene_type=protein_coding;transcript_biotype=protein_coding
pcla8_s000007   CNAG    transcript      8354    20855   .       +       .       ID=Pacla8A056872T2;Parent=Pacla8A056872;Name=Pacla8A056872T2;product=Pacla8A056872P2;gene_type=protein_coding;transcript_biotype=protein_coding;Description=ABC transporter G family member 14 isoform X3;Ontology_term=GO:0005524%2C GO:0016020%2C GO:0016887
`

**Comment by tida-one** [comment]
I solved it and I will put it here just in case it can help someone.

The problem comes from my gff3 file which is only for coding regions. Accordingly the GO terms are added on the lines with "transcript"  in the third column. I just replace (awk) "transcript" by "gene" in the third column and snp2go runs perfectly. 

The reason is that "gene" pattern is targeted by the [ProcessGFF] function that digest the GFF file inside the snp2go function.

**Comment by davidszkiba** [comment]
Hello,
I'm happy that you could resolve it. Thanks for sharing your solution!
